name: 🐛 Bug Report
description: Create a report to help us improve Dev API Play House
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux (Ubuntu, Debian, Fedora, Arch)
        - macOS (Apple Silicon M1-M4)
        - macOS (Intel)
        - Windows 10/11
        - Docker
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: e.g. Python 3.10.12
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Start server with 'python3 app.py'
        2. Go to '...'
        3. Click on '....'
        4. See error
    validations:
      required: true
